* https://84200.blog.luogu.org/
* https://333333.blog.luogu.org/
* https://unthique.github.io/
* https://www.cnblogs.com/xrdrsp
* https://www.luogu.com.cn/blog/gy070421/
* https://www.xrdrsp.pw/
* https://www.zhihu.com/people/xrdrsp
* https://xrdrsp.home.blog/
* https://xrdrsp.github.io/
